# Generated by Django 4.1.7 on 2023-04-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyShelfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=64)),
                ('bookName', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=32)),
            ],
        ),
    ]
